OrdererOrgs:
  - Name: OrdererOrg
    Domain: saintrivers.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs: 
  - Name: Org1
    Domain: org1.saintrivers.com
    EnableNodeOUs: true
    Specs:
      - Hostname: devpeer
        CommonName: devpeer
    Users: 
      Count: 2